### ISSUE TITLE
Question: Linux compatible?

### ISSUE THREAD

**Issue by tmr83** [slyautomation/osrs_basic_botting_functions#3]
I am having trouble using your code because of the win32gui requirement. I cannot install it on my system because of: ModuleNotFoundError: No module named 'winreg'

**Comment by slyautomation** [comment]
got you covered, updated core.py to use the linux version to get the window of Runelite/OpenOSRS. you can delete any reference to win32gui if needed

**Comment by UndescriptDev** [comment]
Thanks a million. I tried running core.py with win32gui commented out, but now I get an invalid syntax error at line 10. Plus Jedi says there are more errors after that.

**Comment by UndescriptDev** [comment]
Will this work for pybot-config.yaml?

- Config:
    client_title: Runelite
    file_path_to_client: /usr/bin/runelite
    pc_profile: /home/user/
    tesseract_path: /usr/bin/tesseract

I got this output:

Traceback (most recent call last):
  File "/home/user/osrs_basic_botting_functions/miner.py", line 3, in <module>
    from functions import Image_count
  File "/home/user/osrs_basic_botting_functions/functions.py", line 43, in <module>
    for f in os.listdir(filename):
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/\\jagexcache\\oldschool\\LIVE\\'
