### ISSUE TITLE
Question: Windows Setup - core.py Win32gui

### ISSUE THREAD

**Issue by RbotJ** [slyautomation/osrs_basic_botting_functions#6]
New python user trying to set this up for a few days now. I pulled with pycharm per the docs and I'm trying to run just core.py, thinking its a good starting point to start understanding, and am getting the following error: `No module named 'win32gui'`

I have tried a pip install command which fails, as well as file/setting/python interpreter to install the win32gui package which both result in a similar error:  `Getting requirements to build wheel ... error`

Wanted to check if there is something obvious I'm missing to set it up, or if a new package has replaced it.

**Comment by tmr83** [comment]
Try installing pywin32

**Comment by tmr83** [comment]
Sorry, I am just some passer by who tried to Google something for you. I don't even use Windows or Pycharm. And no, you shouldn't be trying to import pywin32.

**Comment by slyautomation** [comment]
yep thats correct once you have installled pywin32 using pip install pywin32 or through the requirements.txt. and to reference win32gui. for some reason you can't directly installled win32gui or win32api you have to install the bundled pywin32. so your project should refresh just after install and recognise 'import win32gui' in the python script. 

Hope this helps. in the future i'll probably copy the code of win32gui and repackage it to python library just so its easier for everyone to use.

**Comment by tmr83** [comment]
In the pywin32 repo, it says:

If you encounter any problems when upgrading (eg, "module not found" errors or similar), you should execute:

python Scripts/pywin32_postinstall.py -install

See if that helps...
