### ISSUE TITLE
resizeImage()

### ISSUE THREAD

**Issue by staggy** [slyautomation/osrs_basic_botting_functions#7]
First off i love this project and want to help contribute.

But im having some trouble on initial setup.

my resizeImage() is giving me a window that is not on the text at all it seems to be down and to the right for some reason.

**Comment by staggy** [comment]
Even the screenshot.png is not showing the game window, im missing part of the right image, half the inventory is gone.

**Comment by slyautomation** [comment]
Thanks staggy! Really appreciate your feedback and i'll add the monitor and text of apps solution to the front page.
